// <auto-generated />
using System;
using CellCultureBank.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CellCultureBank.DAL.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CellCultureBank.DAL.Models.BankOfCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Certification")
                        .HasColumnType("bit");

                    b.Property<bool>("Clearing")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateOfDefrosting")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfFreezing")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefrostedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FrozenByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefrostedByUserId");

                    b.HasIndex("FrozenByUserId");

                    b.ToTable("BankOfCells");
                });

            modelBuilder.Entity("CellCultureBank.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CellCultureBank.DAL.Models.BankOfCell", b =>
                {
                    b.HasOne("CellCultureBank.DAL.Models.User", "DefrostedByUser")
                        .WithMany("DefrostedBankSeconds")
                        .HasForeignKey("DefrostedByUserId");

                    b.HasOne("CellCultureBank.DAL.Models.User", "FrozenByUser")
                        .WithMany("FrozenBankSeconds")
                        .HasForeignKey("FrozenByUserId");

                    b.Navigation("DefrostedByUser");

                    b.Navigation("FrozenByUser");
                });

            modelBuilder.Entity("CellCultureBank.DAL.Models.User", b =>
                {
                    b.Navigation("DefrostedBankSeconds");

                    b.Navigation("FrozenBankSeconds");
                });
#pragma warning restore 612, 618
        }
    }
}
